# Generated by Django 5.0.6 on 2024-05-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityProgramsView2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_kodu', models.TextField(blank=True, null=True)),
                ('universite_turu', models.TextField(blank=True, null=True)),
                ('universite', models.TextField(blank=True, null=True)),
                ('fakultesi', models.TextField(blank=True, null=True)),
                ('puan_turu', models.TextField(blank=True, null=True)),
                ('burs_turu', models.TextField(blank=True, null=True)),
                ('genel_kontenjan', models.TextField(blank=True, null=True)),
                ('okul_birincisi_kontenjani', models.TextField(blank=True, null=True)),
                ('toplam_kontenjan', models.TextField(blank=True, null=True)),
                ('genel_kontenjana_yerlesen', models.TextField(blank=True, null=True)),
                ('okul_birincisi_kontenjanina_yerlesen', models.TextField(blank=True, null=True)),
                ('toplam_yerlesen', models.TextField(blank=True, null=True)),
                ('bos_kalan_kontenjan', models.TextField(blank=True, null=True)),
                ('ilk_yerlesme_orani', models.TextField(blank=True, null=True)),
                ('yerlesip_kayit_yaptirmayan', models.TextField(blank=True, null=True)),
                ('ek_yerlesen', models.TextField(blank=True, null=True)),
                ('katsayi_0_12_puani', models.TextField(blank=True, null=True)),
                ('katsayi_0_12_0_06_puani', models.TextField(blank=True, null=True)),
                ('katsayi_0_12_basari_sirasi', models.TextField(blank=True, null=True)),
                ('katsayi_0_12_0_06_basari_sirasi', models.TextField(blank=True, null=True)),
                ('tavan_puan_2023', models.TextField(blank=True, null=True)),
                ('tavan_basari_sirasi_2023', models.TextField(blank=True, null=True)),
                ('obp_kirilmis_2022_2023', models.TextField(blank=True, null=True)),
                ('ortalama_obp', models.TextField(blank=True, null=True)),
                ('ortalama_diploma_notu', models.TextField(blank=True, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'university_programs_view_2',
                'managed': False,
            },
        ),
    ]
