# Generated by Django 5.0.6 on 2024-05-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_universityprogramsview2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='universityprogramsview2',
            table='university_programs_view_3',
        ),
    ]
