# Generated by Django 5.0.6 on 2024-05-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_universityprogramsview2_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenelBilgilerLast2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_code', models.TextField(blank=True, null=True)),
                ('number_0_12_0_06_katsayı_ile_yerleşen_son_kişinin_başarı_sıras', models.TextField(blank=True, db_column='0,12 + 0,06 Katsayı ile Yerleşen Son Kişinin Başarı Sıras', null=True)),
                ('number_0_12_0_06_katsayı_ile_yerleşen_son_kişinin_puanı_field', models.TextField(blank=True, db_column='0,12 + 0,06 Katsayı ile Yerleşen Son Kişinin Puanı*', null=True)),
                ('number_0_12_katsayı_ile_yerleşen_son_kişinin_başarı_sırası_field', models.TextField(blank=True, db_column='0,12 Katsayı ile Yerleşen Son Kişinin Başarı Sırası*', null=True)),
                ('number_0_12_katsayı_ile_yerleşen_son_kişinin_puanı_field', models.TextField(blank=True, db_column='0,12 Katsayı ile Yerleşen Son Kişinin Puanı*', null=True)),
                ('number_2022_de_yerleşip_2023_de_obp_si_kırılarak_yerleşen_sayısı', models.TextField(blank=True, db_column="2022'de Yerleşip 2023'de OBP'si Kırılarak Yerleşen Sayısı", null=True)),
                ('number_2023_tavan_başarı_sırası_0_12_field', models.TextField(blank=True, db_column='2023 Tavan Başarı Sırası(0,12)*', null=True)),
                ('number_2023_tavan_puan_0_12_field', models.TextField(blank=True, db_column='2023 Tavan Puan(0,12)*', null=True)),
                ('boş_kalan_kontenjan', models.TextField(blank=True, db_column='Boş Kalan Kontenjan', null=True)),
                ('burs_türü', models.TextField(blank=True, db_column='Burs Türü', null=True)),
                ('ek_yerleşen', models.TextField(blank=True, db_column='Ek Yerleşen', null=True)),
                ('fakülte_yüksekokul', models.TextField(blank=True, db_column='Fakülte / Yüksekokul', null=True)),
                ('genel_kontenjan', models.TextField(blank=True, db_column='Genel Kontenjan', null=True)),
                ('genel_kontenjana_yerleşen', models.TextField(blank=True, db_column='Genel Kontenjana Yerleşen', null=True)),
                ('okul_birincisi_kontenjanı', models.TextField(blank=True, db_column='Okul Birincisi Kontenjanı', null=True)),
                ('okul_birincisi_kontenjanına_yerleşen', models.TextField(blank=True, db_column='Okul Birincisi Kontenjanına Yerleşen', null=True)),
                ('puan_türü', models.TextField(blank=True, db_column='Puan Türü', null=True)),
                ('toplam_kontenjan_field', models.TextField(blank=True, db_column='Toplam Kontenjan**', null=True)),
                ('toplam_yerleşen', models.TextField(blank=True, db_column='Toplam Yerleşen', null=True)),
                ('yerleşenlerin_ortalama_diploma_notu_field', models.TextField(blank=True, db_column='Yerleşenlerin Ortalama Diploma Notu*', null=True)),
                ('yerleşenlerin_ortalama_obp_si_field', models.TextField(blank=True, db_column="Yerleşenlerin Ortalama OBP'si*", null=True)),
                ('yerleşip_kayıt_yaptırmayan', models.TextField(blank=True, db_column='Yerleşip Kayıt Yaptırmayan', null=True)),
                ('ösym_program_kodu', models.TextField(blank=True, db_column='ÖSYM Program Kodu', null=True)),
                ('üniversite', models.TextField(blank=True, db_column='Üniversite', null=True)),
                ('üniversite_türü', models.TextField(blank=True, db_column='Üniversite Türü', null=True)),
                ('i_lk_yerleşme_oranı', models.TextField(blank=True, db_column='İlk Yerleşme Oranı', null=True)),
                ('bolum_adi', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genel_bilgiler_last_2024',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'provinces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('rector', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'universities',
                'managed': False,
            },
        ),
    ]
